var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/bookings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__acba098b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_d019f675._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f6a7e34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_cd194de2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_bookings_page_actions_6425a77d.js")
R.m(82366)
module.exports=R.m(82366).exports
