// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/[...rest]" | "/admin/finance" | "/admin/iys-logs" | "/admin/salons" | "/admin/salons/[id]/edit" | "/admin/salons/approvals" | "/admin/service-types" | "/admin/services" | "/admin/settings" | "/admin/subscription-plans" | "/admin/support" | "/admin/types" | "/admin/users" | "/booking/[id]/confirm" | "/booking/[id]/staff" | "/booking/[id]/time" | "/booking/[id]/user-info" | "/bookings" | "/customer/appointments" | "/customer/dashboard" | "/customer/favorites" | "/customer/notifications" | "/customer/payments" | "/customer/profile" | "/customer/reviews" | "/customer/settings" | "/customer/support" | "/customer/support/[id]" | "/login" | "/owner/calendar" | "/owner/campaigns" | "/owner/dashboard" | "/owner/onboarding" | "/owner/reports" | "/owner/salons" | "/owner/salons/[id]/edit" | "/owner/services" | "/owner/settings" | "/owner/settings/billing" | "/owner/staff" | "/register" | "/register/business" | "/register/invite" | "/saas" | "/salon-slug/[slug]" | "/salon/[id]" | "/staff/dashboard" | "/staff/hours" | "/staff/profile" | "/staff/schedule"
type AppRouteHandlerRoutes = "/api/auth/send-email-otp" | "/api/auth/verify-email" | "/api/auth/verify-phone" | "/api/booking/available-slots" | "/api/booking/cancel" | "/api/booking/create" | "/api/booking/get-busy-slots" | "/api/booking/send-otp" | "/api/booking/verify-and-book" | "/api/cron/reminders" | "/api/iyzico/sub-merchant/create" | "/api/iyzico/webhook" | "/api/subscription/subscribe"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/booking/[id]" | "/customer" | "/owner" | "/salon-slug/[slug]" | "/salon/[id]" | "/staff"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/[...rest]": { "rest": string[]; }
  "/admin/finance": {}
  "/admin/iys-logs": {}
  "/admin/salons": {}
  "/admin/salons/[id]/edit": { "id": string; }
  "/admin/salons/approvals": {}
  "/admin/service-types": {}
  "/admin/services": {}
  "/admin/settings": {}
  "/admin/subscription-plans": {}
  "/admin/support": {}
  "/admin/types": {}
  "/admin/users": {}
  "/api/auth/send-email-otp": {}
  "/api/auth/verify-email": {}
  "/api/auth/verify-phone": {}
  "/api/booking/available-slots": {}
  "/api/booking/cancel": {}
  "/api/booking/create": {}
  "/api/booking/get-busy-slots": {}
  "/api/booking/send-otp": {}
  "/api/booking/verify-and-book": {}
  "/api/cron/reminders": {}
  "/api/iyzico/sub-merchant/create": {}
  "/api/iyzico/webhook": {}
  "/api/subscription/subscribe": {}
  "/booking/[id]": { "id": string; }
  "/booking/[id]/confirm": { "id": string; }
  "/booking/[id]/staff": { "id": string; }
  "/booking/[id]/time": { "id": string; }
  "/booking/[id]/user-info": { "id": string; }
  "/bookings": {}
  "/customer": {}
  "/customer/appointments": {}
  "/customer/dashboard": {}
  "/customer/favorites": {}
  "/customer/notifications": {}
  "/customer/payments": {}
  "/customer/profile": {}
  "/customer/reviews": {}
  "/customer/settings": {}
  "/customer/support": {}
  "/customer/support/[id]": { "id": string; }
  "/login": {}
  "/owner": {}
  "/owner/calendar": {}
  "/owner/campaigns": {}
  "/owner/dashboard": {}
  "/owner/onboarding": {}
  "/owner/reports": {}
  "/owner/salons": {}
  "/owner/salons/[id]/edit": { "id": string; }
  "/owner/services": {}
  "/owner/settings": {}
  "/owner/settings/billing": {}
  "/owner/staff": {}
  "/register": {}
  "/register/business": {}
  "/register/invite": {}
  "/saas": {}
  "/salon-slug/[slug]": { "slug": string; }
  "/salon/[id]": { "id": string; }
  "/staff": {}
  "/staff/dashboard": {}
  "/staff/hours": {}
  "/staff/profile": {}
  "/staff/schedule": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/booking/[id]": never
  "/customer": never
  "/owner": never
  "/salon-slug/[slug]": never
  "/salon/[id]": never
  "/staff": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
