// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/[...rest]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[...rest]">> = Specific
  const handler = {} as typeof import("../../../app/admin/[...rest]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/iys-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/iys-logs">> = Specific
  const handler = {} as typeof import("../../../app/admin/iys-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/salons/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/salons/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/admin/salons/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/salons/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/salons/approvals">> = Specific
  const handler = {} as typeof import("../../../app/admin/salons/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/salons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/salons">> = Specific
  const handler = {} as typeof import("../../../app/admin/salons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/service-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/service-types">> = Specific
  const handler = {} as typeof import("../../../app/admin/service-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../../app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/subscription-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscription-plans">> = Specific
  const handler = {} as typeof import("../../../app/admin/subscription-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../../app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/types">> = Specific
  const handler = {} as typeof import("../../../app/admin/types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking/[id]/confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/[id]/confirm">> = Specific
  const handler = {} as typeof import("../../../app/booking/[id]/confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking/[id]/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/[id]/staff">> = Specific
  const handler = {} as typeof import("../../../app/booking/[id]/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking/[id]/time/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/[id]/time">> = Specific
  const handler = {} as typeof import("../../../app/booking/[id]/time/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking/[id]/user-info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/[id]/user-info">> = Specific
  const handler = {} as typeof import("../../../app/booking/[id]/user-info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings">> = Specific
  const handler = {} as typeof import("../../../app/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/appointments">> = Specific
  const handler = {} as typeof import("../../../app/customer/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/customer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/favorites">> = Specific
  const handler = {} as typeof import("../../../app/customer/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/notifications">> = Specific
  const handler = {} as typeof import("../../../app/customer/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/payments">> = Specific
  const handler = {} as typeof import("../../../app/customer/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/profile">> = Specific
  const handler = {} as typeof import("../../../app/customer/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/reviews">> = Specific
  const handler = {} as typeof import("../../../app/customer/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/settings">> = Specific
  const handler = {} as typeof import("../../../app/customer/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/support/[id]">> = Specific
  const handler = {} as typeof import("../../../app/customer/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/support">> = Specific
  const handler = {} as typeof import("../../../app/customer/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/calendar">> = Specific
  const handler = {} as typeof import("../../../app/owner/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/campaigns">> = Specific
  const handler = {} as typeof import("../../../app/owner/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/owner/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/owner/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/reports">> = Specific
  const handler = {} as typeof import("../../../app/owner/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/salons/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/salons/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/owner/salons/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/salons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/salons">> = Specific
  const handler = {} as typeof import("../../../app/owner/salons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/services">> = Specific
  const handler = {} as typeof import("../../../app/owner/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/settings/billing">> = Specific
  const handler = {} as typeof import("../../../app/owner/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/settings">> = Specific
  const handler = {} as typeof import("../../../app/owner/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/staff">> = Specific
  const handler = {} as typeof import("../../../app/owner/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/business">> = Specific
  const handler = {} as typeof import("../../../app/register/business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/invite">> = Specific
  const handler = {} as typeof import("../../../app/register/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/saas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saas">> = Specific
  const handler = {} as typeof import("../../../app/saas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/salon-slug/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salon-slug/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/salon-slug/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/salon/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/salon/[id]">> = Specific
  const handler = {} as typeof import("../../../app/salon/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/staff/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/hours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/hours">> = Specific
  const handler = {} as typeof import("../../../app/staff/hours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/profile">> = Specific
  const handler = {} as typeof import("../../../app/staff/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/schedule">> = Specific
  const handler = {} as typeof import("../../../app/staff/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/send-email-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-email-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/send-email-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/verify-phone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-phone">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/verify-phone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/booking/available-slots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/available-slots">> = Specific
  const handler = {} as typeof import("../../../app/api/booking/available-slots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/booking/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/booking/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/booking/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/create">> = Specific
  const handler = {} as typeof import("../../../app/api/booking/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/booking/get-busy-slots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/get-busy-slots">> = Specific
  const handler = {} as typeof import("../../../app/api/booking/get-busy-slots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/booking/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/send-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/booking/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/booking/verify-and-book/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/verify-and-book">> = Specific
  const handler = {} as typeof import("../../../app/api/booking/verify-and-book/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/reminders">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/iyzico/sub-merchant/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iyzico/sub-merchant/create">> = Specific
  const handler = {} as typeof import("../../../app/api/iyzico/sub-merchant/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/iyzico/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iyzico/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/iyzico/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscription/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/subscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/subscription/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/booking/[id]">> = Specific
  const handler = {} as typeof import("../../../app/booking/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../../app/customer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../../app/owner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/salon-slug/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/salon-slug/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/salon-slug/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/salon/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/salon/[id]">> = Specific
  const handler = {} as typeof import("../../../app/salon/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../app/staff/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
