var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/customer/favorites/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d097acbe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_5373bb17._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f6a7e34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_cd194de2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_customer_layout_tsx_6f587491._.js")
R.c("server/chunks/ssr/_next-internal_server_app_customer_favorites_page_actions_ad821474.js")
R.m(88797)
module.exports=R.m(88797).exports
