var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/owner/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__032f39cf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_2a0a1c12._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f6a7e34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_cd194de2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_owner_layout_tsx_05130008._.js")
R.c("server/chunks/ssr/_next-internal_server_app_owner_dashboard_page_actions_a641f38f.js")
R.m(99743)
module.exports=R.m(99743).exports
